Enable `winsup` test suite compilation (#12)
* Enable winsup test suite compilation

User_malloc is temporarily removed due to compilation errors, workaround to
allow the testsuite to reach completion and display the summary.
mingw/cygload test is excluded due to the toolchain limitations.
Removing cygdrop $cygrun to make the tests pass while testing on wsl-env.

* Workaround for undefined reference to `_environ`

---------

Co-authored-by: Radek Bartoň <radek.barton@microsoft.com>